"""empty message

Revision ID: 132fb88cf94f
Revises: 2e0818c81a4f
Create Date: 2025-05-06 14:52:23.322343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132fb88cf94f'
down_revision = '2e0818c81a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.Integer(), nullable=False))
        batch_op.drop_column('orbital_period_days')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orbital_period_days', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('size')

    # ### end Alembic commands ###
